# Generated by Django 6.0.4 on 2026-05-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('vereda', models.CharField(max_length=100)),
                ('area_total', models.FloatField()),
                ('tipo_suelo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('tipo_suelo', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_PREPARACION', 'En preparación'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.finca')),
            ],
        ),
        migrations.CreateModel(
            name='LaborTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_labor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('nivelacion', models.BooleanField(default=False)),
                ('drenaje', models.BooleanField(default=False)),
                ('adecuacion', models.BooleanField(default=False)),
                ('estado_terreno', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='core.lote')),
            ],
        ),
    ]
