# Generated by Django 6.0.4 on 2026-05-10 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('variedad', models.CharField(max_length=100)),
                ('densidad_siembra', models.FloatField(help_text='kg/ha o similar')),
                ('metodo_siembra', models.CharField(choices=[('DIRECTA', 'Siembra directa'), ('TRASPLANTE', 'Trasplante')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siembras', to='core.lote')),
            ],
        ),
    ]
