# Generated by Django 6.0.4 on 2026-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siembra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siembra',
            name='metodo_siembra',
            field=models.CharField(choices=[('DIRECTA', 'Siembra directa'), ('TRASPLANTE', 'Trasplante'), ('VOLEO', 'Voleo')], max_length=20),
        ),
    ]
