# Generated by Django 6.0.4 on 2026-04-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lote_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_labor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado_terreno', models.CharField(max_length=100)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='core.lote')),
            ],
        ),
    ]
