# Generated by Django 6.0.4 on 2026-05-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siembra_metodo_siembra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAgronomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizante', models.CharField(max_length=100)),
                ('cantidad_fertilizante', models.FloatField()),
                ('fecha_fertilizacion', models.DateField()),
                ('control_malezas', models.BooleanField(default=False)),
                ('metodo_malezas', models.CharField(blank=True, max_length=100)),
                ('producto_fitosanitario', models.CharField(blank=True, max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('etapa_fenologica', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.lote')),
            ],
        ),
    ]
