# Generated by Django 6.0.4 on 2026-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_laborterreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborterreno',
            name='adecuacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborterreno',
            name='drenaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborterreno',
            name='nivelacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborterreno',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
