# Generated by Django 6.0.4 on 2026-04-22 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_lote_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloProductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del ciclo (ej. 'Ciclo 2024-A').", max_length=100, unique=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inicia formalmente el ciclo productivo.')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha estimada o real de cierre del ciclo. Puede quedar vacía.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ciclo está actualmente en curso.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo Productivo',
                'verbose_name_plural': 'Ciclos Productivos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField(help_text='Fecha en que se realizó la siembra. No puede ser futura.')),
                ('variedad', models.CharField(help_text="Nombre de la variedad de arroz sembrada (ej. 'Fedearroz 67').", max_length=120)),
                ('densidad', models.DecimalField(blank=True, decimal_places=2, help_text='Densidad de siembra en kg/ha. Campo opcional.', max_digits=7, null=True)),
                ('metodo', models.CharField(choices=[('directa', 'Siembra directa'), ('trasplante', 'Trasplante')], default='directa', help_text='Método de siembra utilizado: directa o trasplante.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la siembra en el sistema.')),
                ('ciclo', models.ForeignKey(help_text='Ciclo productivo al que pertenece esta siembra.', on_delete=django.db.models.deletion.PROTECT, related_name='siembras', to='siembra.cicloproductivo')),
                ('lote', models.ForeignKey(help_text='Lote físico donde se realizó la siembra.', on_delete=django.db.models.deletion.PROTECT, related_name='siembras', to='core.lote')),
            ],
            options={
                'verbose_name': 'Siembra',
                'verbose_name_plural': 'Siembras',
                'ordering': ['-fecha_siembra'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'ciclo'), name='unique_siembra_por_lote_y_ciclo')],
            },
        ),
    ]
