# Generated by Django 6.0.4 on 2026-04-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_lote_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloProductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('variedad_planificada', models.CharField(blank=True, choices=[('IR42', 'IR42'), ('FEDEARROZ_50', 'Fedearroz 50'), ('FEDEARROZ_67', 'Fedearroz 67'), ('FEDEARROZ_174', 'Fedearroz 174'), ('OTRA', 'Otra')], max_length=20)),
                ('fecha_inicio_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='core.lote')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ciclos.cicloproductivo')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_preparacion_estimada', models.DateField()),
                ('fecha_siembra_estimada', models.DateField()),
                ('fecha_manejo_estimada', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField()),
                ('fecha_preparacion_real', models.DateField(blank=True, null=True)),
                ('fecha_siembra_real', models.DateField(blank=True, null=True)),
                ('fecha_cosecha_real', models.DateField(blank=True, null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion', to='ciclos.cicloproductivo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cicloproductivo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PLANIFICADO', 'ACTIVO'])), fields=('lote',), name='unique_ciclo_activo_por_lote'),
        ),
    ]
